steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["compute", "scp", "--recurse", "--tunnel-through-iap", ".", "lakshay_kumar@cluster-0cda-m:/home/lakshay_kumar/", "--zone=us-central1-a"]
options:
  logging: CLOUD_LOGGING_ONLY
