steps:
  #clone checking what already eixst
  - name: ubuntu
    args: 
      - pwd
  #Clone the repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - '-n'
      - $_REPO
      #- .

  #Checkout to branch
  - name: gcr.io/cloud-builders/git
    args:
      - checkout
      - $_BRANCH
  #Install requirements
  - name: 'python:3.8-slim'
    entrypoint: pip
    args:
      - install
      - '-r'
      - ./transformation/requirements.txt
      - '--user'
      - '--no-warn-script-location'

  #Find newly added or modified pipelines
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - "-c"
      - |
          git --no-pager diff --diff-filter=AM --name-only HEAD^ HEAD | grep "transformation/" | cut -d/ -f2 | sort | uniq > changed_dirs.txt
          echo "newly added or modified dataflow pipelines are:"
          cat changed_dirs.txt
          pwd
          ls
          ls transformation
  # #test
  # - name: 'python:3.8'
  #   entrypoint: python3
  #   args:
  #     - crowdstrike_aidmaster.py
  #     - --template_location
  #     - gs://dummy_df_template/Template/aidmaster
  #   dir: ./transformation
  # Template Creation and push to GCS
  - name: 'python:3.8'
    entrypoint: bash
    args:
      - '-c'
      - |
        filename="/workspace/changed_dirs.txt"
        echo "running run.sh"
        while IFS= read -r p || [[ -n "$p" ]]; do
            pipeline="$p"
            if [ "$p" == "." ];then
                echo "No pipelines updated or added"
                break
            fi
            if [ "$p" = "setup.py" ] || [ "${p: -3}" != ".py" ];then
                echo "non python file or setup.py"
                continue
            fi
            echo "Template location will be gs://dummy_df_template/Template/${p:0:-3}_template"
            python3 "$pipeline" --template_location "gs://dummy_df_template/Template/${p:0:-3}_template"
        done < "$filename"
    dir: transformation

substitutions:
  _REPO: >-
    https://gitlab+deploy-token-1485744:hKQFvzYQx8PLk9sqD6KZ@gitlab.com/njccic-collection/EDW-ETL.git
  _BRANCH: dataflow-template-cicd-test 
